### ISSUE TITLE
PyRocky: ansys-rocky-core does not find module named 'requests'

### ISSUE THREAD

**Issue by gabrielgonini** [ansys/pyrocky#119]
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### 🐞 Description of the bug

Reporting the following error in PyRocky: No module named 'requests'. This happens when executing the notebook example Particle simulation with wall interaction. For now, the workaround is to ask the user to install 'requests'.

### 📝 Steps to reproduce

Using a kernel where no other package was installed, execute the notebook example Particle simulation with wall interaction.

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

No additional packages, just the pyrocky installation as in the instructions.

**Comment by igortg** [comment]
The `requests` library is not supposed to be a dependency of PyRocky. It'll be required only to download files used in the example scripts.

We did a small change on the Examples docs for this requirement to be more noticeable:
https://rocky.docs.pyansys.com/version/dev/examples/index.html
