### ISSUE TITLE
Modify  the getting started instruction to load pyrocky

### ISSUE THREAD

**Issue by lkostetzer** [ansys/pyrocky#44]
### Description of the modifications

In Getting started / Launch PyRocky
https://github.com/ansys/pyrocky/blob/main/doc/source/getting_started/index.rst

There is a wrong command to load pyrocky.

Now we have:  
import ansys.rocky.rocky as pyrocky

But this should be 
import ansys.rocky.core as pyrocky

**Comment by tk-koellner** [comment]
Encountered the same problem.
